### PR TITLE
Added getwheat.ca

### PR DESCRIPTION
**Pull request by hotdoy**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

*Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

```
- domain:
  url: https://getwheat.ca/
  size: 343
  last_checked: 2022/01/30
```

GTMetrix Report: 
https://gtmetrix.com/reports/getwheat.ca/jYXxBBbo/

### CODE REVIEW

**Comment by kevquirk** [comment]
I used to use Grav back in the day, but had constant issues with the RSS feed for some reason, so I ditched it in the end. I should really re-visit it to see if it has matured.

**Comment by hotdoy** [comment]
It has been my platform of choice for 2 years now. You had issue with an RSS plugin? Templating an RSS should be relatively easy without a plugin really. 

Anyways, give it a spin again! It really turned out into something nice since 1.7 and premium plugins.

**Comment by kevquirk** [comment]
Yeah, we're going back a few years here, so I didn't have the knowledge to build my own xml feed file, so I was stuck with a plugin.

I'll have to take it for a spin again...

**Comment by hotdoy** [comment]
Hit me up in the Grav Discord if you need pointers. I'm always lurking.

**Pull request merged**
