### PR TITLE
Update sites.yml (adding cri.cl)

### PR DESCRIPTION
**Pull request by dejalavidavolar**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: cri.cl
  url: https://cri.cl/
  size: 72.0
  last_checked: 2022-03-03
```

GTMetrix Report: https://gtmetrix.com/reports/cri.cl/j8eLYR7R/

### CODE REVIEW

**Comment by dejalavidavolar** [comment]
> GT Metrix link has expired

Link updated! 👍

**Comment by garritfra** [comment]
Great site! Thanks for your submission.

**Comment by dejalavidavolar** [comment]
Thanks to you!!

**Comment by dejalavidavolar** [comment]
@kevquirk @garritfra I made this "old school retro web banner" for anyone who wants to use it on their website (1.1kb).

512kb

Regards!

**Pull request merged**
