### PR TITLE
Add arcadewise.me

### PR DESCRIPTION
**Pull request by l3gacyb3ta**
This PR is:

- [X] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [X] I used the uncompressed size of the site
- [X] I have included a link to the GTMetrix report
- [X] The domain is in the correct alphabetical order
- [X] This site is not a ultra lightweight site
- [X] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [X ] Check to confirm

```yaml
- domain: arcadewise.me
  url: https://arcadewise.me/
  size: 248
  last_checked: 2022-05-20
```

GTMetrix Report: <https://gtmetrix.com/reports/arcadewise.me/0aKwGcW4/>

### CODE REVIEW

**Comment by garritfra** [comment]
According to the report, the size is 258, not 248 kB. Typo?🙂

**Review by garritfra — CHANGES_REQUESTED** [review]
According to the report, the site is 258, not 248 kB. Typo?🙂

**Comment by l3gacyb3ta** [comment]
ah damn, sorry!

**Comment by l3gacyb3ta** [comment]
Okie dokie! I fixed it.

**Review by garritfra — APPROVED** [review]

**Pull request merged**
