### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by nicolastjt**
https://gtmetrix.com/reports/thejollyteapot.com/Z6QMDfFp/

**Important:** Please read all instructions carefully.

_Select the appropriate category for what this PR is about_

This PR is:

- [ ] Adding a new domain
- [X] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

*Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

- [X] I used the uncompressed size of the site
- [X] I have included a link to the GTMetrix report
- [X] The domain is in the correct alphabetical order
- [X] This site is not a ultra lightweight site
- [X] The following information is filled identical to the data file

```
- domain: thejollyteapot.com
  url: https://thejollyteapot.com/
  size: 6.79
  last_checked: 2022-01-22
```

GTMetrix Report: https://gtmetrix.com/reports/thejollyteapot.com/Z6QMDfFp/

### CODE REVIEW

**Comment by kevquirk** [comment]
Just been perusing your blog - I really like it, nice job! I've considered Blot myself, but ended up going with Jekyll.

**Comment by nicolastjt** [comment]
Thanks for the compliment. It means a lot! Yeah, Blot really is great, and worry-free. I keep a look on Hugo, Jekyll, and Vue (even VitePress) but it’s too complicated for me.

**Comment by kevquirk** [comment]
I was previously using WordPress, but [Jekyll ended up being the simpler option](https://kevq.uk/goodbye-wordpress-switched-to-jekyll/). Blot would be even more simple...I'm tempted to try it out.

**Comment by nicolastjt** [comment]
Only thing to bear in mind is that there is no control the server: both a good thing and a bad thing. The creator, David, is very helpful in any case.

**Pull request merged**
