### PR TITLE
housekeeping

### PR DESCRIPTION
**Pull request by ttntm**
This PR is:

- [ ] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [x] Other not listed

This PR is taking care of #1453 

removed the following sites

- https://fz1.space
- https://saucecode.bar
- https://closedgl2.github.io
- https://notes.whoibrar.com
- https://chibilinks.com
- https://hund.tty1.se
- https://sverona.dev
- https://stapy.magentix.fr
- https://eg-zine.cf
- https://ARC-X.org

kept the following sites

- https://luana.cc -- personal site, looks ok
- https://vern.cc -- valid, no issue
- https://arc-x.org -- not listed in `sites.yml`
- https://sm6kne.amprnet.se -- valid
- https://huma.id -- valid

updated sites:

- https://www.0chris.com >> https://www.stchris.net

### CODE REVIEW

**Comment by ttntm** [comment]
> Thanks for checking them again, seems like some of them had issues that are now resolved

good point!

I updated the listing and re-checked the size, seems it's  still the old site, just a new TLD.

**Comment by ttntm** [comment]
> And arc-x is listed in the yaml but it's all uppercase
> 
> https://github.com/kevquirk/512kb.club/blob/d4a086cd6c09b55879ee46df19449cf914a68cb1/_data/sites.yml#L66

perfect, got it, thanks!

**Comment by garritfra** [comment]
Thanks for this!

Let me know when you're ready. Looks good to me so far. 👍

**Comment by ttntm** [comment]
> Thanks for this!
> 
> Let me know when you're ready. Looks good to me so far. 👍

Everything reported in the linked issue should be in this PR by now, good to go IMO.

**Comment by garritfra** [comment]
Thank you!

**Pull request merged**
