### PR TITLE
Add uncenter.org

### PR DESCRIPTION
**Pull request by uncenter**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: uncenter.org
  url: https://www.uncenter.org/
  size: 69.3
  last_checked: 2023-02-20
```

GTMetrix Report: 
https://gtmetrix.com/reports/uncenter.org/hjIE57Pp/

### CODE REVIEW

**Comment by uncenter** [comment]
> Sorry to say, but I must categorize this as ultra-minimal content as defined by our [FAQ](https://512kb.club/faq). Thanks anyway!

I didn't think it was super minimal - apologies! What is the "threshold" for a non-minimal site? I would love to apply again later (assuming having more posts and such on the site would qualify it at some point).

**Comment by garritfra** [comment]
It's not a hard rule. Generally, we're trying to show what's possible with 512kB of space. The paragraph on your page hints that there might be something cool there soon. Be creative - I'd love to see the result! 🙂

**Comment by uncenter** [comment]
Hey @garritfra! Almost been a year since I first made this ahah. Do you think my website qualifies now? The URL is now https://uncenter.dev/ FYI (thought it does redirect from the old one).

**Comment by garritfra** [comment]
Hi, that's a great website! Feel free to open a new PR (or update this one) and I'd be happy to merge it. 🙂

**Pull request closed without merging**
