### PR TITLE
adding aaronjeskie.com

### PR DESCRIPTION
**Pull request by ajesk**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: aaronjeskie.com
  url: https://aaronjeskie.com/
  size: 35.4
  last_checked: 2022-04-08
```

GTMetrix Report: 
https://gtmetrix.com/reports/aaronjeskie.com/0SVIRdPb/

### CODE REVIEW

**Comment by garritfra** [comment]
Whoops, I hit merge to quickly. Could you fix the alphabetical ordering?

**Comment by ajesk** [comment]
@garritfra will do. I wasn't entirely sure where I would fall there. I am guessing I need to be after aaron.place?

**Comment by garritfra** [comment]
@ajesk yep, the "." character comes after j. :)

**Comment by ajesk** [comment]
all taken care of in the other pr :)

**Comment by garritfra** [comment]
Awesome, thank you!

**Pull request merged**
