### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by scag1io**
Added https://scaglio.id - https://radar.cloudflare.com/scan/9e74551a-de38-45d4-bc33-7f1fcb85fd06

This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the Cloudflare report
- [x] This site is not an ultra minimal site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: scaglio.id
  url: https://scaglio.id/
  size: 174.17
  last_checked: 2024-04-10
```

Cloudflare Report: https://radar.cloudflare.com/scan/9e74551a-de38-45d4-bc33-7f1fcb85fd06

### CODE REVIEW

**Comment by garritfra** [comment]
Hmm, this seems right to me. @kevquirk could you check the deployment logs?

**Comment by kevquirk** [comment]
Apparently I had to approve the deployment

**Comment by scag1io** [comment]
I tried to remove the /summary at the end of the Cloudlflare URL. Maybe was it causing the issue?

**Comment by garritfra** [comment]
The cloudflare report is just a manual review process, so it shouldn't interfer with the build and deployment. 🤔 The code looks good though. @kevquirk do you mind checking vercel again?

**Comment by scag1io** [comment]
I'm closing this PR and I'll open another one (I also fixed the size of another website of mines). We'll see if Vercel will get mad again. Thank you!

**Pull request closed without merging**
