### PR TITLE
Remove sitejs.org

### PR DESCRIPTION
**Pull request by aafomin**
**Important:** Please read all instructions carefully.

_Select the appropriate category for what this PR is about_

This PR is:

- [ ] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [x] Removing existing domain from list
- [ ] Website code changes
- [ ] Other not listed

*Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [ ] The domain is in the correct alphabetical order
- [ ] This site is not a ultra lightweight site
- [ ] The following information is filled identical to the data file

```
- domain: sitejs.org
  url: https://sitejs.org/
  size: 709
  last_checked: 2021-07-21
```

GTMetrix Report: https://gtmetrix.com/reports/sitejs.org/Ldo3x8oA/

### CODE REVIEW

**Comment by kmutahar** [comment]
Could I ask why you are removing 2 sites.

**Comment by aafomin** [comment]
> Could I ask why you are removing 2 sites in one PR. Each domain should be a separate PR

I pushed a new commit to my master after creating a PR
My bad
No cheating meant 😉
Will correct soon

**Comment by kmutahar** [comment]
I figured it was something like that

And thank you for your help. I you want to make it easier you can do something like #417 with a table with domain, reason, and GTmetrik report in one PR.

**Comment by aafomin** [comment]
Thank you
Will keep in mind

As for the initial issue. I dropped the last commit
Please check

**Pull request merged**
