### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by arjun4s**
**Important:** Please read all instructions carefully.

_Select the appropriate category for what this PR is about_

This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

*Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

- [ ] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [ ] The domain is in the correct alphabetical order
- [ ] This site is not a ultra lightweight site
- [ ] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

[ ] Check to confirm

```
- domain: jagatsoker.blogspot.com
  url: https://jagatsoker.blogspot.com/
  size: 179
  last_checked: 2022-02-03 (YYYY-MM-DD)
```

GTMetrix Report:
https://gtmetrix.com/reports/jagatsoker.blogspot.com/Ifnht7XH/#waterfall

### CODE REVIEW

**Comment by kmutahar** [comment]
Please fix the date by removing  (YYYY-MM-DD)

**Comment by arjun4s** [comment]
Hi! I removed  (YYYY-MM-DD) as your request. Please, check again. Thank you.

**Comment by arjun4s** [comment]
- domain: jagatsoker.blogspot.com
  url: https://jagatsoker.blogspot.com/
  size: 179
  last_checked: 2022-02-03

**Comment by kmutahar** [comment]
from the commit it self

**Comment by arjun4s** [comment]
I'm sorry I don't understand so I made pull request again (https://github.com/kevquirk/512kb.club/pull/697)

**Comment by kevquirk** [comment]
This qualifies as ultra-minimal. Won't be merging, sorry.

**Pull request closed without merging**
