### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by colinmcdermott**
This PR is:

- [x] Adding a new domain
- [x] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [ ] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [ ] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain:
  url:
  size:
  last_checked:
```

GTMetrix Report:

### CODE REVIEW

**Comment by garritfra** [comment]
Do you mind fixing the alphabetical order?

**Comment by colinmcdermott** [comment]
Hi @garritfra my apologies, I got a bit overwhelmed (I'm still learning some aspects of GitHub) - will try again!

**Comment by colinmcdermott** [comment]
Okay, I think we have lift-off! 🚀

**Comment by garritfra** [comment]
LGTM🙂

**Pull request merged**
