### PR TITLE
add raikas.dev

### PR DESCRIPTION
**Pull request by raikasdev**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: raikas.dev
  url: https://raikas.dev/
  size: 4.8
  last_checked: 2022-05-08
```

GTMetrix Report: https://gtmetrix.com/reports/raikas.dev/FfJlzyNy/

### CODE REVIEW

**Comment by garritfra** [comment]
Uhh, creative!

I don't want to ruin the fun, but according to the report, your site is 4.85 kb. Just to be fair with the rest, could you update the value?

**Review by garritfra — CHANGES_REQUESTED** [review]
Branch also has merge conflicts.

**Comment by raikasdev** [comment]
Fixed conflicts and corrected size.

**Review by garritfra — APPROVED** [review]
Thanks a lot, LGTM!

**Pull request merged**
