### PR TITLE
Update sebastianrasor.com

### PR DESCRIPTION
**Pull request by sebastianrasor**
Update size: https://gtmetrix.com/reports/www.sebastianrasor.com/tjuNABLQ/
Block requests to favicon.ico, which increases the file size of the only file but decreases overall request size.

### CODE REVIEW

**Comment by kmutahar** [comment]
After checking your site I believe it falls under the "ultra-lightweight sites" and should not be include, and will refer this to @kevquirk 

> There are a growing number of "sites" being submitted to The 512KB Club that are ultra lightweight (usually <1KB). These sites often contain absolutely no information apart from a couple of links to other pages that do contain information.
> 
> These sites are not in keeping with the aim of The 512KB Club and will not be added. To be added to this site the page you submit must contain a reasonable amount of information.
> 
> But what qualifies as a "reasonable amount of information"?
> 
> Great question! Ultimately it's for me to decide and I will use my own discretion, but as a guide, if your site contains nothing more than a title and a couple of links, it won't be added. If you page contains some CSS formatting, a couple of paragraphs of text, and links to other pages, it will probably be added.
> 
> The aim of The 512KB Club is to showcase lightweight websites. Anyone can create a website that is under 1KB, but composed only of a single h1 tag and a couple of links. That's boring - try and be more interesting.

**Comment by sebastianrasor** [comment]
My site contains more than a title and a couple of links.
It contains CSS formatting, points that describe me, and links to other pages.

**Comment by kmutahar** [comment]
You are correct and that is why I referred it to Kev.

**Comment by kevquirk** [comment]
Yup, I agree with @kmutahar this falls under the "ultra minimal" caveat. Sorry.

**Comment by sebastianrasor** [comment]
Would it be different if I had added some more CSS or something? I see sites with far less information than my own, and my site was already removed prior to blocking the favicon request.

**Comment by kevquirk** [comment]
Your site, along with quite a few others were added before I added the caveat. I started noticing a trend, so I added it.

We will work our way through and remove the applicable sites at some point.

WRT what you need to do, it's not about CSS, it's about the content of the site AND its design. A very small `<ul>` and a couple of links to other pages (which also don't contain a great deal of info) isn't really what the 512kb Club is about.

It's about showcasing what can be done with 512kb of data, not how brutalist a site can be.

**Comment by sebastianrasor** [comment]
Alright, thanks for the clarification.

**Pull request closed without merging**
