### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by ghost**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [ ] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: haxi.viw.se
  url: https://haxi.viw.se
  size: 51.6
  last_checked: 2022 02 27
```

GTMetrix Report: https://gtmetrix.com/reports/haxi.viw.se/7Hf8feCk/

### CODE REVIEW

**Comment by kevquirk** [comment]
Please include a GT Metrix link.

**Comment by thatcatdrout** [comment]
Added!

**Comment by thatcatdrout** [comment]
let me fix it

**Comment by garritfra** [comment]
Also, the date should have this format: `yyyy-mm-dd`. It's missing the `-`.

**Pull request closed without merging**
