### PR TITLE
add a script to recheck sites at gtmetrix

### PR DESCRIPTION
**Pull request by Lex-2008**
This PR is:

- [x] Other not listed

Note that I'm not sure where to put this file, so just added it to the root. Please correct me :)
Actually, its proper place is in the root of https://github.com/aisayko/python-gtmetrix/ repo :/

Steps:
1. register at gtmetrix.com
2. open [account](https://gtmetrix.com/dashboard/account) section
2. In the Your Plan - API Usage, generate API key.
   Also note that upon registration, you're given 100 credits "for testing", and every day at noon Vancouver time your credits are refilled _up to_ 10 (so only if you have less than 10). We need only the most basic kind of report, which costs 0.7 credits, hence we can request 10/0.7=14 reports per day.
3. install python-gtmetrix
  While they have a pip project, there is a [comment](https://github.com/aisayko/python-gtmetrix/issues/13#issuecomment-781785672) suggesting to install from git. In my case, I just cloned their repo and put this script into its root (next to setup.py). From all their requirements.txt file they seem to need only [requests][req] which have [pip][req-pip] and an [OS package][req-os].
4. Install "ruamel.yaml" Python library (available via [pip][yml-pip] or a [package manager][yml-arch]) if you haven't done it before (it's same library used by my previous script https://github.com/kevquirk/512kb.club/issues/386#issuecomment-892792390)
4. next to your script, create myauth.py file with a content like this:
    ````
    email='email@example.com'
    api_key='96bcab1060d838723701010387159086'
    ````
    with email which you used to register at gtmetrix.com (step 1) and api key which you got on step 3
5. As of writing, this script fails on the https://dejalavidavolar.org/ (ref https://github.com/kevquirk/512kb.club/issues/448), so edit `last_checked` value for this site to be a valid date (for example, `2021-04-11`).
5. Run this script like this:
    ````
    python script2.py ../512kb.club/_data/sites.yml 1
    ````
    where 1 is the number of websites to be updated (starting with oldest ones)
6. If everything goes right, you should get a table-like output which you can just paste into Guthub PR:
    ````
    Site | old size (team) | new size (team) | delta (%) | GTMetrix | note
    ---- | --------------- | --------------- | --------- | -------- | ----
    [docs.j7k6.org](https://docs.j7k6.org/) | 73.0kb (green) | 72.9kb (green) | -0.1kb (-0%) | [report](https://gtmetrix.com/reports/docs.j7k6.org/PkIra4ns/#waterfall) | 
    ````
    Note that it "hangs" for about 30 seconds in the middle of each line except first two: first it prints site name and old size, then waits for gtmetrix scan to finish, and after that prints new size, delta, etc.
7. Create a PR like this one: https://github.com/kevquirk/512kb.club/pull/445

[req]: http://python-requests.org/
[req-pip]: https://pypi.org/project/requests/
[req-os]: https://archlinux.org/packages/extra/any/python-requests/
[yml-pip]: https://pypi.org/project/ruamel.yaml/
[yml-arch]: https://archlinux.org/packages/community/any/python-ruamel-yaml/

Note: currently this script doesn't check any errors returned by gtmetrix API. That's next item on my list. Moreover, I'd like to get rid of python-gtmetrix dependency, since it feels like it adds more troubles than benefits.

### CODE REVIEW

**Comment by kmutahar** [comment]
Hey just a heads up there is a syntax error (terminal output)

```
  File "script2.py", line 90
    print(f"[{site['domain']}]({site['url']}) | {oldsize:.1f}kb ({oldteam}) | ", end='', flush=True)
                                                                              ^
SyntaxError: invalid syntax
```

**Comment by kmutahar** [comment]
Reply to this comment so as to keep everything in one place https://github.com/kevquirk/512kb.club/pull/445#issuecomment-894679874


So the script will places in a documentation or script folder with the how-to guide you just wrote and anything else needed to make it easier for others to use. Said folder will be excluded from the Jekyll site deployment so it wont affect the site in anyway

**Comment by Lex-2008** [comment]
SyntaxError fixed! Also, can you tell me what version of Python are you using?

**Comment by Lex-2008** [comment]
you mentioned a possibility to run this script by several people in parallel - I thought about it and I think I know how it can be implemented. I'll let you know when I make amends. For now, we have to take turns when running this script

**Comment by kmutahar** [comment]
So I tried the updated script and it didn't work at first it was then that I noticed I was using python2 oops.

so the way I was thinking multiple people could work in parallel is basically one person would start open a PR and the next person would commit onto said PR and then the next person so on so on. This way doesn't require edits to the script just one person at a time.

I will leave this PR open until you tell me to merge it. I am perfectly fine with how the code is so far.


Just one note the new update dropped the "|" at the start and end of each entry. Not a big problem since markdown understands what is happening

**Comment by Lex-2008** [comment]
oh, right, sorry, for the Python 2 vs 3 confusion - should've mentioned it in the beginning. Yes, I believe Python3 is a requirement of one of the libraries this script is using. I believe it's possible to change it when getting rid of python-gtmetrix dependency, but I already see you managed to run this script. So do you want me to try to make it Python2-compatible or are you fine with having Python3?

Regarding multiple people working on the same PR - right, I haven't thought about it. Good idea!

Regarding the vertical bar "|" at the start and end of each entry - I was using [this guide][g] from markdown (linked in bottom-right corner when composing a comment), and they didn't put it there in the example. So maybe it's better to follow their "recommendation"?

[g]: https://guides.github.com/features/mastering-markdown/#:~:text=Tables

Before merging this PR - let me copy the first comment to a markdown file next to the script so we have documentation in the repo, too.

**Comment by kmutahar** [comment]
It's okay about Python3 I was working on a virtual server and forgot that I didn't alias python to be python3, still trying to learn python. 

As for the markdown let us just follow GitHub's guide since this is all happening on site. 

You can go ahead and create the documentation and do anything that is needed I won't Merge until you give me the go-ahead. if you need anything let me know.

**Comment by Lex-2008** [comment]
@kmutahar: docs added to this PR are the best to my knowledge. Feel free to amend them as you see fit (maybe you can add your experience of installing/using this script?) and merge.

I'll open a new PR when I have a better version of this script (probably in ~1 week, unless an urgent bug pops up).

**Pull request merged**
