### PR TITLE
adding new website

### PR DESCRIPTION
**Pull request by youknow16**
https://gtmetrix.com/reports/samic.org/lTjTtgiH/

This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: samic.org
  url: https://samic.org/
  size: 18.4
  last_checked: 2022-04-15
```

GTMetrix Report: https://gtmetrix.com/reports/samic.org/lTjTtgiH/

### CODE REVIEW

**Comment by garritfra** [comment]
@kmutahar UM?🤔

**Comment by kmutahar** [comment]
I'm going to go with light weight

**Comment by garritfra** [comment]
@kmutahar fair.👍

@youknow16 thanks for your PR!

**Comment by garritfra** [comment]
Dang, I shouldn't use GH mobile to trigger action runs. I'll fix the ordering in a bit.

**Pull request merged**
