### PR TITLE
add: fmaartingr.com (and github action to automate measurement)

### PR DESCRIPTION
**Pull request by fmartingr**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [x] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: fmartingr.com
  url: https://fmartingr.com
  size: 143
  last_checked: 2022-03-13
```

GTMetrix Report: https://gtmetrix.com/reports/fmartingr.com/KEBm6omw/

---

This PR also contains a Github Action Job to automatically determine the website uncompressed size using [puppeteer](https://github.com/puppeteer/puppeteer).

The script runs a headless chrome instance and checks all received data from the URL to calculate it's size, and the job fails if the result in kilobytes is larger than 512. It does not fully automate the process but it may help with reviewing.

Test PR action: https://github.com/fmartingr/512kb.club/runs/5528640938

Screenshot 2022-03-13 at 17 32 17

Some improvements that could be made:
- Usage of [danger](https://danger.systems) to comment automatically on the PR based on PR results.
- A fully automated system:
  - Users commit new URLs to a `sites.txt` (can be txt, yaml, w/e) file with a simple format:
     ``` txt
     https://site1.com
     https://site2.com
     ```
     In this file domains can be pushed directly to the end of the file since we do not need them to be sorted, also since it's only one line per domain we could just `cat sites | sort` anyway.
  - [On PR] Measure page size to check if it fits the 512kb.club.
  - [On merge to master] Check out files not present on this file and fill out a new `sites_parsed.yaml` with the same format as the current `sites.yaml` (though this one is filled automatically).
  - [On a certain schedule] Check sites that hasn't been tested for a while and measure their size again, updating the parsed file as needed.
  - [On a certain schedule] Remove URLs from `sites.yaml` that aren't present on `sites_parsed.yaml` (does not meet criteria).

As a note, measurement can also be done using `wget` but with the added problem that it downloads every linked asset on the site regardless if it's used on the URL or not, an example from my site:

```
$ wget -p -H 'https://fmartingr.com/'  2>&1 >/dev/null | tail -n 1
Downloaded: 12 files, 313K in 0,03s (8,92 MB/s)
```

it's more because it also download several fonts not currently being used.

Let me know what you think about it!

### CODE REVIEW

**Comment by garritfra** [comment]
Thanks for your PR! I really like where you're headed, but using puppeteer for this job doesn't feel right. GTMetrix has a REST API that we could use to retrieve the information from a test run, either by parsing the report ID from the existing run, or by enqueueing a new run and waiting for it to be done. What do you think?

https://gtmetrix.com/api/docs/2.0/

**Comment by kmutahar** [comment]
Hey @fmartingr The Idea sounds good, however before we start maybe you can split this PR into two so that we can properly discuss it.

I also want to add that each method that calculates page size has some difference in how they do it. so we need a standard and then base everything off of it. So we can be using puppeteer, GTMetrix and others all at the same time

**Comment by garritfra** [comment]
@kmutahar 
> I also want to add that each method that calculates page size has some difference in how they do it. so we need a standard and then base everything off of it. So we can be using puppeteer, GTMetrix and others all at the same time

Can you elaborate on this a bit? As far as I can tell, @fmartingr was trying to scrape the GTMetrix website using Puppeteer, which yields the same result as opening the report by hand.

**Comment by kmutahar** [comment]
> The script runs a headless chrome instance and checks all received data from the URL to calculate it's size,

So I understood from this part is that it calculates the size by itself. if its scraping then you are correct it will result in the same, but we may face ToS issues so it needs to be checked

**Comment by fmartingr** [comment]
Just to clarify: this Github Action uses Puppeteer to calculate the size, **it does not use GTMetrix** in any way.

Why? Because GTMetrix is a paid service, it was my first choice since it's described in the readme and so on, but automating an online service that may get down or switch ToC at any moment is pretty inconvenient. That's why I decided to use Puppeteer directly (which is the same or a very similar method used by this kind of sites).

Not sure why you prefer GTMetrix over other solutions, am I missing something here?

I saw a script that already uses GTMetrix to update old sites, if it's mandatory to use the service the script can be called from an Action as well.

**Comment by kevquirk** [comment]
I'm not precious about which tool we use for monitoring website size. The reason I chose GT Metrix was because it is quick and easy to do a scan. I don't want to have to force people to install applications in order to do a scan locally - it shouldn't be that difficult.

If Puppeteer gives the same results (or very close) and there's a way for people to scan using it online, I'm happy to switch.

**Comment by garritfra** [comment]
Some thoughts:
Using puppeteer as a GH action makes it harder for contributors to verify the page size when opening a PR. The current workflow is as follows:
1. Check GTMetrix
2. Open a PR with the GTMetrix result
3. Wait for a maintainer to review the PR

If the contributor doesn't have puppeteer installed (which, I suspect, a lot of them don't), they'd have to:
1. Check GTMetrix
4. Open a PR with the GTMetrix result
5. Wait for a maintainer to approve the workflow run
6. Wait for the Puppeteer result
7. Potentially update the PR with the Puppeteer results
8. Wait for a maintainer to review the PR

This is quite tedious in my opinion.

**Comment by fmartingr** [comment]
I wasn't expecting this much movement about this change 😓 

I initially started this as a simple help for maintainers so they can check easily if a site at least is <512kb just by checking if a test passed or not, but I forgot about the workflow approval, which makes it a bit more tedious.

As I said, it can be done exactly like that but using the GTMetrix API or scrapping the test results but: 
- GTMetrix API is paid (and a external service). Already put my comments about this [here](https://github.com/kevquirk/512kb.club/pull/749#issuecomment-1067333737).
- I don't know about how hard would it be to scrape the test results, and any significant (or not so) will break the workflow action.

Those two options still have the same problem about the workflow requiring to be approved.

I'm unsure how to move forward.

**Comment by kmutahar** [comment]
First of all movement and discussion is an important part of things like this, since they foster creativity and new ideas, so it's a good thing. 

GTMetrix API while it is paid they do offer a free service that would check about 10 sites per day, which is more than enough and we can always check the rest manually. I currently use it with the current script that checks old sites size (You can see the development history of the script and the process of it coming to life done by @Lex-2008 in Issue #386, #445, and #449 )

**Comment by fmartingr** [comment]
> First of all movement and discussion is an important part of things like this, since they foster creativity and new ideas, so it's a good thing.
> 
> GTMetrix API while it is paid they do offer a free service that would check about 10 sites per day, which is more than enough and we can always check the rest manually. I currently use it with the current script that checks old sites size (You can see the development history of the script and the process of it coming to life done by @Lex-2008 in Issue #386, #445, and #449 )

So just to be clear and move this forward properly:
- Disable this workflow (moving the file outside the `.github/workflows` folder so we can re-enable it in the future if needed)
- Create a new workflow that uses the GTMetrix API to fetch the uncompressed size, failing the action if it is more than 512KB
- This workflow should also fail if the request fails dure to not having enough credits.

Is this alright?

Sorry this is taking some time, I have some situation at home and I do not have a much available time as I want 😓

**Comment by garritfra** [comment]
I'm sorry that this PR is kind of stale. 

I propose to remove the script and just add your site. I really appreciate your effort to improve our review process though!

**Comment by fmartingr** [comment]
> I'm sorry that this PR is kind of stale.
> 
> I propose to remove the script and just add your site. I really appreciate your effort to improve our review process though!

No problemo! Just reverted the commit.

**Comment by garritfra** [comment]
LGTM!

**Comment by danger89** [comment]
You can actually keep the file in the workflow folder. But just add ".disabled" to the end of the filename.

**Pull request merged**
