### PR TITLE
Update sites.yml (add "cri.cl")

### PR DESCRIPTION
**Pull request by dejalavidavolar**
Gtmetrix results: https://gtmetrix.com/reports/cri.cl/M03pBAzk/

**Important:** Please read all instructions carefully.

_Select the appropriate category for what this PR is about_

This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

*Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

```
- domain: cri.cl
  url: https://cri.cl/
  size: 5.43
  last_checked: 2022-01-21
```

GTMetrix Report: https://gtmetrix.com/reports/cri.cl/M03pBAzk/

### CODE REVIEW

**Comment by kevquirk** [comment]
Site isn't responding. Also looks like this would qualify as "ultra minimal" so I won't be merging.

More info here: https://512kb.club/faq

**Comment by dejalavidavolar** [comment]
Hi, that's sad to hear. The site is staying online, I have had no problems with the server. Regarding whether it qualifies as "ultra-lightweight", I am adding posts to my blog, could there be a reconsideration?

Regards

**Comment by kevquirk** [comment]
It's not about what on the blog. It's about what's on home page and the design. Take a look at the faq for more details. Sorry.

**Comment by dejalavidavolar** [comment]
I understand. What about now? Can you check please? The design of my page is different now. 

Regards

**Comment by dejalavidavolar** [comment]
(https://cri.cl)

**Pull request closed without merging**
