### PR TITLE
Add tty1.blog

### PR DESCRIPTION
**Pull request by benjaminbhollon**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: tty1.blog
  url: https://tty1.blog/
  size: 19.5
  last_checked 2023-05-07
```

GTMetrix Report: https://gtmetrix.com/reports/tty1.blog/QRj9UNki/

### CODE REVIEW

**Comment by benjaminbhollon** [comment]
I think I got that all right—it's saying it's out of alphabetical order, but I fixed that. Unless I'm missing something.

**Comment by garritfra** [comment]
Where I'm from, "T" comes after "R" in the alphabet. 😉

**Comment by benjaminbhollon** [comment]
Oh, so *that's* why there wasn't anything else starting with t.

I blame it on sleep deprivation. XD

**Comment by benjaminbhollon** [comment]
Okay *this* time it should be alphebitized right. :joy:

**Comment by garritfra** [comment]
It looks like the deploy gods don't want to see this merged.😅 @kevquirk could you take a look?

**Comment by kevquirk** [comment]
It's missing a colon on the line date checked line:

`last_checked 2023-05-07`

**Comment by benjaminbhollon** [comment]
Wow, I was more sleep deprived than I thought. XD

**Comment by benjaminbhollon** [comment]
*sigh* alright I think it works this time.

**Comment by garritfra** [comment]
Yup. Thanks!

**Pull request merged**
