### PR TITLE
combine data files into one file

### PR DESCRIPTION
**Pull request by kmutahar**
combine the file and have the liquid code sort and show the appropriate sites based on size

@kevquirk @lrmikestone 

Before this is merged will make the final commit in creating a `sites.yml` file that merges the 3 files in alphabetical order.

### CODE REVIEW

**Comment by kmutahar** [comment]
This is a great source for liquid commands https://shopify.github.io/liquid/

**Comment by kmutahar** [comment]
@kevquirk @lrmikestone If both of you are good with this let me know and I will edit the documentation and merge it.

To test it locally create `_data/sites.yml` and paste in it the domains from the 3 old data files.

**Comment by kevquirk** [comment]
I'll need to have a closer look at this, as it seems the deployment is failing:

```
2:04:27 PM:   Liquid Exception: Liquid error (line 38): Cannot sort a null object. in index.md
2:04:27 PM:                     ------------------------------------------------
2:04:27 PM:       Jekyll 4.2.0   Please append `--trace` to the `build` command 
2:04:27 PM:                      for any additional information or backtrace. 
2:04:27 PM:                     ------------------------------------------------
```

**Comment by kmutahar** [comment]
Make sure you created a new data file called `sites.yml`

**Comment by kevquirk** [comment]
Your PR fails to build though, so the site will break is we merge it, won't it?

**Comment by kmutahar** [comment]
For before the merge I will create one last commit that creates the 'sites.yml' file and delete the current '<color>-team.yml' files. And it will pass build.

**Comment by kevquirk** [comment]
I'm confused, why not do that now?

**Comment by kmutahar** [comment]
Sorry for not being clear, it is just in case anyone adds or edits a domain between now and merging into master.

**Comment by kevquirk** [comment]
Ohhhhhh I'm with you now. Makes sense. Let's get it merged so that doesn't happen then. If you have tested it, and it works, then I'm happy. We can always revert if needed.

**Comment by kmutahar** [comment]
Steps I used to sort the data file automatically.

After merging all the files into one location I converted it [from YAML to JSON](https://onlineyamltools.com/convert-yaml-to-json) and saved said output into a new file called `out.json`

Using [jq](https://stedolan.github.io/jq/) used the following command to sort the JSON file using the `domain` key
```bash
cat out.json | jq 'sort_by(.domain)' > clean-json.json
```

took clean-json.json and converted it from [JSON to YAML](https://onlineyamltools.com/convert-json-to-yaml) and cleaned up the formatting manually using Find & Replace in VSCode text editor

**Comment by kevquirk** [comment]
I assume this is a one time deal? I hope we don't have to do this every time a domain is added.

**Comment by kmutahar** [comment]
Oh yes it's a one time deal. Just documenting it just in case since the same thing can be used to sort by other key pairs.

**Pull request merged**
