### PR TITLE
Add krzysckh.org

### PR DESCRIPTION
**Pull request by krzysckh**
**Important:** Please read all instructions carefully.

_Select the appropriate category for what this PR is about_

This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes
- [ ] Other not listed

*Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

```
- domain: krzysckh.org
  url: http://krzysckh.org
  size: 0.8
  last_checked: 2021-08-21
```

GTMetrix Report:
https://gtmetrix.com/reports/krzysckh.org/1q6TEq6S/

### CODE REVIEW

**Comment by kmutahar** [comment]
Hi I am sorry but this site falls under the lightweight sites

**Comment by krzysckh** [comment]
> Hi I am sorry but this site falls under the lightweight sites

Hi
how does my site fall under lightweight sites but maczan.pl (2nd smallest on 512kb.club) doesn't? it has the same amount of info as mine lol

Sorry for bothering, but that seems a little unfair ;/

**Comment by kevquirk** [comment]
We're trying to retrospectively review all sites in the list for being ultra minimal, but it takes time.

The site you mentioned does qualify as ultra minimal too, so we will be removing it along with any others we find.

Hope that helps.

**Comment by krzysckh** [comment]
thanks for your response,, hope i can join y'all in the future when my site grows ;) 

love ya, krzych <3

**Pull request closed without merging**
