### PR TITLE
changed url and updated size for my blog

### PR DESCRIPTION
**Pull request by pasdechance**
This PR is:

- [ ] Adding a new domain
- [X] Updating existing domain **size**
- [X] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [X] I used the uncompressed size of the site
- [X] I have included a link to the GTMetrix report
- [X] The domain is in the correct alphabetical order
- [X] This site is not a ultra lightweight site
- [X] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [X] Check to confirm

```
- domain: bbbhltz.codeberg.page
  url: bbbhltz.codeberg.page
  size: 29.1
  last_checked: 2022-03-06
```

GTMetrix Report: [https://gtmetrix.com/reports/bbbhltz.codeberg.page/1er57rua/](https://gtmetrix.com/reports/bbbhltz.codeberg.page/1er57rua/)

### CODE REVIEW

**Comment by kevquirk** [comment]
This site falls into the 'ultra-minimal' bucket I'm afraid, so I won't be merging this one. Sorry.

**Comment by pasdechance** [comment]
Hi

the site bbbhltz.codeberg.page is not ultraminimal, the previous url was deleted and contains a link to the new url.

**Comment by kevquirk** [comment]
It is I'm afraid.

**Comment by pasdechance** [comment]
okay.

**Pull request closed without merging**
