### PR TITLE
add xnacly.me to domains

### PR DESCRIPTION
**Pull request by xNaCly**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [ ] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: xnacly.me
  url: https://xnacly.me
  size: 37.9
  last_checked: 2022-09-12
```

GTMetrix Report: https://gtmetrix.com/reports/xnacly.me/TYH7UtnY/

### CODE REVIEW

**Review by garritfra — CHANGES_REQUESTED** [review]
Please use the uncompressed size of the page.

**Comment by xNaCly** [comment]
> Please use the uncompressed size of the page.

How do i even do that, i can only see the compressed size of the page

**Comment by xNaCly** [comment]
> Please use the uncompressed size of the page.

Done.

**Comment by xNaCly** [comment]
> It seems like you didn't review our [FAQ](https://512kb.club). :)
> 
> The site should be added in alphabetical order.

Oh well, didnt see that down there

**Review by garritfra — APPROVED** [review]

**Pull request merged**
