### PR TITLE
Added vili.dev

### PR DESCRIPTION
**Pull request by V1li**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: vili.dev
  url: https://vili.dev/
  size: 502
  last_checked: 2023-03-27
```

GTMetrix Report: 
https://gtmetrix.com/reports/vili.dev/VQstecZF/

### CODE REVIEW

**Review by garritfra — CHANGES_REQUESTED** [review]
Do you mind fixing the alphabetical order?

**Comment by V1li** [comment]
Oops, yeah ima fix that.

**Comment by V1li** [comment]
It is in the order tho..? Its under the last domain that starts with the letter **V**.

**Comment by garritfra** [comment]
> It is in the order tho..? Its under the last domain that starts with the letter **V**.

Where I'm from, `vv` comes *after* `vi`. ;)

https://en.wikipedia.org/wiki/Alphabetical_order

**Review by garritfra — APPROVED** [review]

**Pull request merged**
