### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by Gamer555DT**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: saber.tk
  url: https://saber.tk/
  size: 105
  last_checked: 2022-07-26
```

GTMetrix Report: https://gtmetrix.com/reports/saber.tk/fevrPk9H/

### CODE REVIEW

**Comment by garritfra** [comment]
@kevquirk do we want to include hosted services, in this case SearXNG?🤔

**Comment by Gamer555DT** [comment]
> @kevquirk do we want to include hosted services, in this case SearXNG?🤔

Are hosted services not allowed?

**Comment by kevquirk** [comment]
No. I don't think this is in keeping with the motivations for the project. What do you think, @garritfra?

**Comment by garritfra** [comment]
> No. I don't think this is in keeping with the motivations for the project. What do you think, @garritfra? 

Fully with you.👍

**Pull request closed without merging**
