### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by RMoore35**
Request addition to the 512kb club. I used to be a part of it but was probably removed at some point ... 

Link to scan below:

https://radar.cloudflare.com/scan/b0899312-a7db-40e3-9cd8-9fde78691db0/network

This PR is:

- [ x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x ] I used the uncompressed size of the site
- [x ] I have included a link to the Cloudflare report
- [x ] This site is not an ultra minimal site
- [x ] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x ] Check to confirm

```
- domain: rmooreblog.netlify.app
  url: https://rmooreblog.netlify.app/
  size: 30.45
  last_checked: 2024 - 08 - 15
```

Cloudflare Report:  https://radar.cloudflare.com/scan/b0899312-a7db-40e3-9cd8-9fde78691db0/network

### CODE REVIEW

**Comment by garritfra** [comment]
The size doesn't add up. Please use the "Bytes Total" metric

**Comment by RMoore35** [comment]
Updated size: 30.45

**Comment by garritfra** [comment]
Am I missing something? The listing says 2 MB, which is wildly off. 😅

**Comment by RMoore35** [comment]
OK, did this get closed and merged? It says merged. However, I can't find my site on the list.

**Comment by garritfra** [comment]
It seems like it was removed via https://github.com/kevquirk/512kb.club/pull/1756. @kevquirk decided it was too minimal, as per our FAQ. Sorry about that.

**Comment by RMoore35** [comment]
> It seems like it was removed via #1756. @kevquirk decided it was too minimal, as per our FAQ. Sorry about that.

Thanks for the reply!

**Pull request merged**
