### PR TITLE
add edizyurdakul.com to site.yaml

### PR DESCRIPTION
**Pull request by edizyurdakul**
This PR is:

- [✔️] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [✔️] I used the uncompressed size of the site
- [✔️] I have included a link to the GTMetrix report
- [✔️] The domain is in the correct alphabetical order
- [✔️] This site is not a ultra lightweight site
- [✔️] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [✔️] Check to confirm

```
- domain: edizyurdakul.com
  url: https://edizyurdakul.com/
  size: 442
  last_checked: 2022-04-24
```

GTMetrix Report: https://gtmetrix.com/reports/edizyurdakul.com/KgKbkB8k/

### CODE REVIEW

**Comment by garritfra** [comment]
Thanks for adding your site. Mind fixing the alphabetical ordering?

**Comment by edizyurdakul** [comment]
Hi, thanks, is the alphabetical order correct?

**Comment by garritfra** [comment]
Where I'm from, "T" comes before the "Z". 🙂

**Comment by garritfra** [comment]
All good now. Thanks!

**Pull request merged**
