### PR TITLE
Addition of domain: mulph.ie

### PR DESCRIPTION
**Pull request by pachunka**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

*Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

```
- domain: mulph.ie
  url: https://mulph.ie
  size: 196
  last_checked: 2022-01-31
```

GTMetrix Report: https://gtmetrix.com/reports/mulph.ie/bHjeuz65/

--

p.s. Thankyou for making this project!

### CODE REVIEW

**Comment by kevquirk** [comment]
GT Metrix shows 196KB - thought I'd double check with you as 196KB means you get into green team, so you might want to double check and update. :-)

**Comment by pachunka** [comment]
Ah! I'm guessing it doesn't include the favicon, which adds a few KB. :) I had just added everything up from the uncompressed files. I'll update shortly!

**Comment by pachunka** [comment]
hm. My favicon theory doesn't seem true; not sure what I did wrong. Either way I'll update with the slightly-better figure. ;)

**Comment by pachunka** [comment]
Updated! :)

**Pull request merged**
