### PR TITLE
Add eportfoliot.redu.fi/eportfoliot/juusokekonen/ to _data/sites.yml

### PR DESCRIPTION
**Pull request by juu736f**
This PR is:

- [X] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [X] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [X] The domain is in the correct alphabetical order
- [X] This site is not an ultra lightweight site
- [X] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [X] Check to confirm

```
- domain: eportfoliot.redu.fi/eportfoliot/juusokekonen/
  url: https://eportfoliot.redu.fi/eportfoliot/juusokekonen/
  size: 317
  last_checked: 2022-08-29
```

GTMetrix Report: https://gtmetrix.com/reports/eportfoliot.redu.fi/Wm03W1xo/

### CODE REVIEW

**Comment by garritfra** [comment]
@kevquirk do you have feelings towards non-rootpath sites?

**Comment by juu736f** [comment]
> @kevquirk do you have feelings towards non-rootpath sites?

It was a school project and I was required to put it under eportfoliot/juusokekonen. If the length is a problem, and don't want to put it on 512kb.club, no problem, I won't mind.

**Comment by kevquirk** [comment]
Is this still maintained? The URL is less of a problem, but if this was just a short term project that's no longer maintained, I'd rather not add it.

**Comment by juu736f** [comment]
> Is this still maintained? The URL is less of a problem, but if this was just a short term project that's no longer maintained, I'd rather not add it.

I plan to maintain it for as long as I study (the site gets removed after I graduate). It is an online CV, and I will be using it to find a job for work apprenticeship, so keeping the information as up to date as possible is important

**Comment by kevquirk** [comment]
Fine by me then. I'd appreciate it if you could create another PR once you graduate so we can remove it.

**Comment by juu736f** [comment]
> Fine by me then. I'd appreciate it if you could create another PR once you graduate so we can remove it.

Will do! Thank you

**Pull request merged**
