### PR TITLE
Edit to `brycewray.com` entry

### PR DESCRIPTION
**Pull request by brycewray**
Size is reduced due to a redesign (and I now prefer to add `www.` in the `url` if that’s acceptable).

This PR is:

- [ ] Adding a new domain
- [x] Updating existing domain **size**
- [x] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: brycewray.com
  url: https://www.brycewray.com/
  size: 50.3
  last_checked: 2022-05-26
```

GTMetrix Report: 
https://gtmetrix.com/reports/www.brycewray.com/Rb1rUX9g/

### CODE REVIEW

**Comment by garritfra** [comment]
Thanks! According to the report, your site is 92.3 kB uncompressed. Mind fixing that?

**Review by garritfra — CHANGES_REQUESTED** [review]
Thanks! According to the report, your site is 92.3 kB uncompressed. Mind fixing that?

**Review by brycewray — COMMENTED** [review]
Corrected to GTMetrix **uncompressed** report as requested.

**Comment by brycewray** [comment]
@garritfra My apologies for the error! I hadn’t submitted this in a while (nor had I been on GTMetrix in a while), and simply overlooked the distinction between compressed and uncompressed in the report even though I see that I (too hurriedly) checked the box about the uncompressed version.

**Comment by garritfra** [comment]
All good, happens to the best of us. 🙂

LGTM!

**Pull request merged**
