### PR TITLE
Update sites.yml

### PR DESCRIPTION
**Pull request by catdroutcode**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
- domain: catdrout.xyz
  url: https://catdrout.xyz
  size: 313
  last_checked: 2022-05-28
```

GTMetrix Report: https://gtmetrix.com/reports/catdrout.xyz/WD0Kk8lh/

### CODE REVIEW

**Review by garritfra — CHANGES_REQUESTED** [review]
Could you fix the alphabetical ordering? Thanks!

**Comment by catdroutcode** [comment]
Fixed

**Comment by garritfra** [comment]
It seems like you updated the size as well. Do you have a new report as a proof?🙂

**Comment by catdroutcode** [comment]
let me generate a report

**Comment by catdroutcode** [comment]
give me 24 hours i need to fix something real quick

**Comment by catdroutcode** [comment]
Merge

**Comment by garritfra** [comment]
I don't know if the results of Pingdom are on par with what we're using. Let's stick to GTMetrix, to keep it fair with everyone else.

**Comment by kmutahar** [comment]
Just a heads up GTMetrix is what we officially use, however if the site can not be scanned an alternative is used on a case by case.

**Comment by catdroutcode** [comment]
https://gtmetrix.com/reports/catdrout.xyz/2PVmEzlH/

Page size 313 kb uncompressed

**Review by garritfra — APPROVED** [review]

**Pull request merged**
