### PR TITLE
Add bfontaine.net/blog

### PR DESCRIPTION
**Pull request by bfontaine**
**Important:** Please read all instructions carefully.

_Select the appropriate category for what this PR is about_

This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

*Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

```yaml
- domain: bfontaine.net/blog
  url: https://bfontaine.net/blog/
  size: 73.6
  last_checked: 2021-12-12
```

GTMetrix Report: https://gtmetrix.com/reports/bfontaine.net/VqakU0KQ/

### CODE REVIEW

**Comment by kmutahar** [comment]
Hello, I am sorry but we can not accept a page of a domain. You can submit another PR with the main domain only.

**Comment by bfontaine** [comment]
Ok, thank you for the response. If you don’t mind, could you clarify this a bit? Is it that the `domain:` key must point to a domain ([unlike here](https://github.com/kevquirk/512kb.club/blob/ef2070c047b655636be618690a26e37a8f5ea1bb/_data/sites.yml#L616)) but the URL can point to a subpath ([like here](https://github.com/kevquirk/512kb.club/blob/ef2070c047b655636be618690a26e37a8f5ea1bb/_data/sites.yml#L1097)), or is it that for some reason websites that aren’t at the root of the domain are not accepted?

I could submit the root domain but it’s just some text with a couple links, while /blog has “real” content.

**Comment by kmutahar** [comment]
So for the first link, there are problems with accessing the root domain since it is linked to GitLab (don't know how their hosting works)

as for the second link, I believe that it is similar to your situation. So if you can edit this PR and have the ```domain``` key point to the room.

**Comment by bfontaine** [comment]
Done; thank you for the feedback!

**Pull request merged**
