### PR TITLE
Added Page idotmaster1.neocities.org

### PR DESCRIPTION
**Pull request by IdotMaster1**
https://gtmetrix.com/reports/idotmaster1.neocities.org/jWon2obo/

### CODE REVIEW

**Comment by kmutahar** [comment]
Please fix the following

- True size
- remove (YYYY-MM-DD)
- put it in the correct order
- making sure style is correct

**Comment by IdotMaster1** [comment]
done

**Comment by kmutahar** [comment]
I have fixed it for you. Please check the commit and the README again for the future.

**Comment by IdotMaster1** [comment]
Thanks, my brain is too much of a brick

**Pull request merged**
