### PR TITLE
Add my blog, b0ba.dev

### PR DESCRIPTION
**Pull request by tarob0ba**
This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

I have:

- [x] I used the uncompressed size of the site
- [x] I have included a link to the GTMetrix report
- [x] The domain is in the correct alphabetical order
- [x] This site is not a ultra lightweight site
- [x] The following information is filled identical to the data file

***I confirm that I have read the [FAQ section](https://512kb.club/faq), particularly the two red items around minimal pages and inappropriate content and I attest that this site is neither of these things.***

- [x] Check to confirm

```
 - domain: b0ba.dev
  url: https://b0ba.dev/
  size: 504
  last_checked: 2022-04-12
```

GTMetrix Report: https://gtmetrix.com/reports/b0ba.dev/z3cC8Q3L/

### CODE REVIEW

**Comment by tarob0ba** [comment]
Did I mess something up? I see that the CI has failed.

**Comment by kmutahar** [comment]
It happens to the best of us. 

There is still one more error the domain shouldn't be indented

**Comment by tarob0ba** [comment]
Oops.

I'll get on that.

**Comment by tarob0ba** [comment]
Fixed. 🚀

**Pull request merged**
