### PR TITLE
adding stabulation.com

### PR DESCRIPTION
**Pull request by netmonk**
**Important:** Please read all instructions carefully.

_Select the appropriate category for what this PR is about_

This PR is:

- [x] Adding a new domain
- [ ] Updating existing domain **size**
- [ ] Changing domain name
- [ ] Removing existing domain from list
- [ ] Website code changes (512kb.club site)
- [ ] Other not listed

*Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

- [x] I used the uncompressed size of the site
- [ ] I have included a link to the GTMetrix report
- [ ] The domain is in the correct alphabetical order
- [ ] This site is not a ultra lightweight site
- [ ] The following information is filled identical to the data file

```
- domain:
  url:
  size:
  last_checked:
```

GTMetrix Report:

### CODE REVIEW

**Comment by netmonk** [comment]
https://gtmetrix.com/reports/stabulation.com/y2u4HRko/

**Comment by netmonk** [comment]
For information and geek pleasure this site only lives in ram of hugo in server mode docker image with a traefik as frontend 
full information here https://citoyx.com/blogs/docker_traefik_hugo_server/

**Comment by kevquirk** [comment]
How is this site 280KB?? There's nothing there!

Qualifies as ultra-minimal/link only. Won't be merging.

**Comment by netmonk** [comment]
Damn you are rude :) This is a blog with severals articles, i dont understand how you missed that.

**Comment by kevquirk** [comment]
The comment was supposed to be tongue in cheek. Apologies if I came off as rude. Reading it back it does sound rude, sorry about that.

The whole minimal thing is explained on the website FAQ page. Look for the red item:

https://512kb.club/faq

**Comment by netmonk** [comment]
Be aware i read all the FAQ, and that i visited most of the websites in the list. Some of them have fewer text thank mine in their main pages. 

But anyway. you are are the one who decides here. Have a nice evening. 
BTW after looking at waterfall, 70% of the 270kb are google analytic JSes.

**Pull request closed without merging**
